loki:
  config: |
    auth_enabled: false
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_target_size: 1048576
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    limits_config:
      retention_period: ${retention_hours}h
    chunk_store_config:
      max_look_back_period: ${retention_hours}h
    table_manager:
      retention_deletes_enabled: true
      retention_interval: 1h
    retention_table_period: 1h

persistence:
  enabled: true
  storageClassName: "ebs-sc"
  # size: ${storage_size}
  size: 1Gi
  accessModes:
    - ReadWriteOnce
