mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    filelog:
      include: [ /var/log/containers/*.log ]
      start_at: beginning

  processors:
    batch:
    memory_limiter:
      check_interval: 1s
      limit_mib: 500
      spike_limit_mib: 200

  exporters:
    loki:
      endpoint: "${loki_endpoint}"

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheusremotewrite]
      logs:
        receivers: [filelog]
        processors: [batch]
        exporters: [loki]